/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bandtec.projeto04.poo1;

import com.sun.corba.se.impl.orbutil.CorbaResourceUtil;
import java.awt.Color;

/**
 *
 * @author jenni
 */
public class Tela1 extends javax.swing.JFrame {

    /**
     * Creates new form Tela1
     */
    public Tela1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTexto1 = new javax.swing.JLabel();
        lbTexto2 = new javax.swing.JLabel();
        lbTexto3 = new javax.swing.JLabel();
        tfCampo1 = new javax.swing.JTextField();
        tfCampo2 = new javax.swing.JTextField();
        tfCampo3 = new javax.swing.JTextField();
        btAcao1 = new javax.swing.JButton();
        btAcao2 = new javax.swing.JButton();
        btAcao3 = new javax.swing.JButton();
        btAcao4 = new javax.swing.JButton();
        btAcao5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTexto1.setForeground(new java.awt.Color(0, 204, 204));
        lbTexto1.setText("jLabel1");

        lbTexto2.setForeground(new java.awt.Color(204, 0, 0));
        lbTexto2.setText("jLabel2");

        lbTexto3.setForeground(new java.awt.Color(51, 153, 0));
        lbTexto3.setText("jLabel3");

        tfCampo1.setText("Digite aqui");
        tfCampo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCampo1ActionPerformed(evt);
            }
        });

        tfCampo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCampo2ActionPerformed(evt);
            }
        });

        tfCampo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCampo3ActionPerformed(evt);
            }
        });

        btAcao1.setText("Ação 1");
        btAcao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAcao1ActionPerformed(evt);
            }
        });

        btAcao2.setText("Ação 2");
        btAcao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAcao2ActionPerformed(evt);
            }
        });

        btAcao3.setText("Ação 3");
        btAcao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAcao3ActionPerformed(evt);
            }
        });

        btAcao4.setText("Ação 4");
        btAcao4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAcao4ActionPerformed(evt);
            }
        });

        btAcao5.setText("Ação 5");
        btAcao5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAcao5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btAcao1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfCampo1)
                            .addComponent(lbTexto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbTexto2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btAcao2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfCampo2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btAcao3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfCampo3)
                            .addComponent(lbTexto3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(btAcao4)
                        .addGap(18, 18, 18)
                        .addComponent(btAcao5)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTexto1)
                    .addComponent(lbTexto2)
                    .addComponent(lbTexto3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCampo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAcao1)
                    .addComponent(btAcao2)
                    .addComponent(btAcao3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAcao4)
                    .addComponent(btAcao5))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfCampo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCampo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCampo2ActionPerformed

    private void tfCampo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCampo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCampo3ActionPerformed

    private void btAcao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAcao1ActionPerformed
        
        // Pegamos o objeto "lbTexto1"
        // Mudamos seu atributo "text" com setText()
        lbTexto1.setText("É nóis no Java Swing");
        
        // Sempre que vamos mudar um atributo, usamos "setX()"
    }//GEN-LAST:event_btAcao1ActionPerformed

    private void btAcao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAcao2ActionPerformed
        
        // Pegamos o objeto "lbTexto1"
        // Mudamos seu atributo "text" com setText()
        
        lbTexto2.setText(tfCampo2.getText());
    }//GEN-LAST:event_btAcao2ActionPerformed

    private void btAcao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAcao3ActionPerformed
        lbTexto3.setForeground(Color.YELLOW);
    }//GEN-LAST:event_btAcao3ActionPerformed

    private void btAcao5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAcao5ActionPerformed
        lbTexto1.setForeground(lbTexto2.getForeground());
        lbTexto3.setForeground(lbTexto2.getForeground());
    }//GEN-LAST:event_btAcao5ActionPerformed

    private void btAcao4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAcao4ActionPerformed
        lbTexto1.setText(tfCampo1.getText());
        lbTexto2.setText(tfCampo1.getText());
        lbTexto3.setText(tfCampo1.getText());
    }//GEN-LAST:event_btAcao4ActionPerformed

    private void tfCampo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCampo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCampo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAcao1;
    private javax.swing.JButton btAcao2;
    private javax.swing.JButton btAcao3;
    private javax.swing.JButton btAcao4;
    private javax.swing.JButton btAcao5;
    private javax.swing.JLabel lbTexto1;
    private javax.swing.JLabel lbTexto2;
    private javax.swing.JLabel lbTexto3;
    private javax.swing.JTextField tfCampo1;
    private javax.swing.JTextField tfCampo2;
    private javax.swing.JTextField tfCampo3;
    // End of variables declaration//GEN-END:variables
}
